export const FETCH_NEWEST_REPOS_SUCCESS = 'FETCH_NEWEST_REPOS_SUCCESS';
export const FETCH_NEWEST_REPOS_FAILURE = 'FETCH_NEWEST_REPOS_FAILURE';

export const INCREMENT_REPO_RATING = 'INCREMENT_REPO_RATING';
