import React from "react";
import IStyledComponentProps from "../../typescript/interfaces/shared/styled-components/IStyled-React-Component";
import styled from "styled-components";

/**
 * @interface IProps => Component`s props interface.
 */
interface IProps extends IStyledComponentProps {
    url: string;
}


/**
 * @function Url => Common component that encapsulates Hypertext url functionality.
 * @param children => Passed React node.
 * @param className => Class name that is generated by Styled component library.
 * @param url => Target Hypertext url address.
 */
const Url: React.FC<IProps> = ({children, className, url}) => {
    return (
    <a className={className} href={url}>{children}</a>
    )
}

export default styled(Url)``;