import React from "react";

import styled from "styled-components";
import IStyledComponentProps from "../../../typescript/interfaces/shared/styled-components/IStyled-React-Component";
import { Row, Col } from "reactstrap";
import { GithubRepositoryType } from "../../../redux/store/github/types";

import Pagination from "react-js-pagination";


/**
 * @interface IProps => Componwnr's props interfaxe.
 */
interface IProps extends IStyledComponentProps {

    pageNumber: number;
    repositories: GithubRepositoryType[];
    handlePageChange: (pageNumber: number) => void;
}

/**
 * @function GithubRepositoryPagination => Gihub repos pagination system.
 * @param className => class name which is generated by Styled components library.
 * @param handlePageChange => Event handler that handels page toggling.
 * @param pageNumber => Current page identifier.
 * @param repositories => Collection of Github repositories.
 */
const GithubRepositoryPagination: React.FC<IProps> = ({ className, handlePageChange, pageNumber, repositories}) => {

    if (repositories.length === 0) return null;

    return (
        <Row className={className}>
            <Col>
                <Pagination
                    activePage={pageNumber}
                    itemsCountPerPage={5}
                    totalItemsCount={repositories.length}
                    pageRangeDisplayed={12}
                    onChange={handlePageChange}
                    itemClass="page-item"
                    linkClass="page-link"
                />
            </Col>
        </Row>
        
    );
}


export default styled(GithubRepositoryPagination)`
    padding-top: 2.5vh;
`;