import React from "react";

import styled from "styled-components";
import IStyledComponentProps from "../../../typescript/interfaces/shared/styled-components/IStyled-React-Component";
import { Container, Row, Col } from "reactstrap";

/**
 * @function GithubRepositoryListContainer => 
 * @param children => React node which is passed into this parrent component.
 * @param className => classname which is generated by Styled components library.
 */
const GithubRepositoryListContainer: React.FC<IStyledComponentProps> = ({ children, className}) => {
    return (
        <Row className={className}>
            <Col>
                {children}
            </Col>
        </Row>
    );
}

export default styled(GithubRepositoryListContainer)`
    margin-top: 1.5vh;
`