import React from "react";

import styled from "styled-components";
import IStyledComponentProps from "../../../typescript/interfaces/shared/styled-components/IStyled-React-Component";
import { Row, Col } from "reactstrap";

/**
 * @function GithubItemRepository => Stylization parent component of Github repository listing.
 * @param children => React node which is passed into this parrent component.
 * @param className => classname which is generated by Styled components library.
 */
const GithubItemRepository: React.FC<IStyledComponentProps> = ({ children, className}) => {
    return (
        <Row className={className}>
            <Col>
                {children}
            </Col>
        </Row>
    );
}

export default styled(GithubItemRepository)`
    margin-top: 1.5vh;
`